name: Docker Image CI

on:
  workflow_dispatch:

env:
  GITHUB_API_VERSION: 2022-11-28

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get latest release
        id: version
        run: |
          set -eux

          json_response=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: $GITHUB_API_VERSION" \
            https://api.github.com/repos/MCCTeam/Minecraft-Console-Client/releases/latest)

          echo "current_tag=$(echo $json_response | jq -r '.tag_name')" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/minecraft-console-client
          tags: |
            type=raw,value=${{ steps.version.outputs.current_tag }}
            type=raw,value=latest
            type=sha,value=${{ github.sha }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: MCC_VERSION=${{ steps.version.outputs.current_tag }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
